djinstagram/djinstagram/urls.py
from django.conf.urls import url, include
from django.urls import path
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

from instaapp.views import general

urlpatterns = [
    url(r'^$', general.index, name='instaindex'),
    url(r'^admin/', admin.site.urls),
    url(r'^insta/', include('instaapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djinstagram/instaapp/urls.py
from django.conf.urls import url
from django.urls import path
from .views import ajax
from .views import general

app_name = 'instaapp'
urlpatterns = [
    url(r'^$', general.index, name='index'),
    url(r'^login/$', general.user_login, name='user_login'),
    url(r'^viewprofile/$', general.viewprofile, name='viewprofile'),
    url(r'^home/$', general.home, name='home'),
    url(r'^logout/$', general.user_logout, name='user_logout'),
    url(r'^upload/$', general.upload_photo, name='upload_photo'),
    url(r'^users/$', general.users, name='users'),
    url(r'^signup/$', general.signup, name='signup'),
    url(r'^u/(?P<username>[\w-]+)$', general.user_profile, name='user_view'),
    url(r'^profile/$', general.user_profile, name='user_profile'),
    url(r'^following/$', general.user_following, name='user_following'),
    url(r'^followers/$', general.user_followers, name='user_followers'),
    url(r'^feed/$', general.feed, name='feed'),
    url(r'^search/$', general.search, name='user_search'),
    url(r'^otherprofile/$', general.otherprofile, name='otherprofile'),
    url(r'^addsuggest/$', general.suggest, name='suggest'),
    url(r'^delsuggest/$', general.delsuggest, name='delsuggest'),
 

    # AJAX methods
    url(r'^upload_dp/$', ajax.upload_user_profile_pic,
        name='upload_user_profile_pic'),
    url(r'^follow/$', ajax.follow_user, name='follow_user'),
    url(r'^unfollow/$', ajax.unfollow_user, name='unfollow_user'),
    url(r'^post_comment/$', ajax.post_photo_comment, name='post_photo_comment'),
    url(r'^like_comment/$', ajax.like_photo, name='like_photo'),
]

djinstagram/instaapp/views/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()
    

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

djinstagram/instaapp/views/ajax.py
# TODO[10.6.2016]: Refactor code, remove unused imports
# Views for AJAX Requests

import json, itertools

from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect

from django.core.exceptions import MultipleObjectsReturned
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

from instaapp.forms import LoginForm, PhotoForm, MemberPhotoForm
from instaapp.models import Follow, Photo, Member, Comment, Like

from annoying.functions import get_object_or_None
from django.contrib import messages
# Create your views here.

def follow_user(request):
    """
    Method (AJAX) that makes the `logged user` follow the selected user
    """
    data = {
            'status': 0,
        }
    if request.user.is_authenticated:
        if request.method == 'POST':
            follower = User.objects.get(pk=request.user.id)
            following = User.objects.get(pk=request.POST['uid'])
            try:
                follow = Follow(follower=follower, following=following)
                follow.save()
               
            except Follow.MultipleObjectsReturned:
                pass
        
            data = {
                    'status': 1,
                    'follower': request.user.id,
                    'to_follow': request.POST['uid']
                }

            # data to be returned as json

            
    data = json.dumps(data)
    return HttpResponse(data, content_type='application/json')

def unfollow_user(request):
    """
    Method (AJAX) that makes the `logged user` to unfollow a selected user
    """
    data = {
        'status': 0,
    }
    if request.user.is_authenticated:
        if request.method == 'POST':
            # check if logged user is following the selected user
            x = User.objects.get(pk=request.user.id)
            y = User.objects.get(pk=request.POST['uid'])
            
            # follow_obj = get_object_or_None(Follow,
            #                         follower=follower,
            #                         following=following, 
            #                         active=True
            #                         )
            for zzz in Follow.objects.all(): 
                try:
                    follow_obj = Follow.objects.get(follower=x, following=y)
                    follow_obj.delete()
                    data['status'] = 1
               
               
                except Follow.DoesNotExist:
                    pass
                except Follow.MultipleObjectsReturned:
                    dups = Follow.objects.filter(follower=x, following=y)
                    perm = dups[0]
                    for dup in dups[1:]:
                        dup.delete()
                        data['status'] = 1

    data = json.dumps(data)
    return HttpResponse(data, content_type='application/json')

def upload_user_profile_pic(request):
    """
    Method (AJAX) that allows the `logged user` to upload a profile pic
    """
    uploader = request.user
    form = MemberPhotoForm()
    data = {
        'status': 1,
    }

    if request.method == 'POST':
        form = MemberPhotoForm(request.POST, request.FILES)
        if form.is_valid():

            # check if user has already uploaded a profile picture
            existing_dp = get_object_or_None(Member, user__pk=uploader.id)

            obj = form.save(commit=False)
            obj.user = uploader

            if existing_dp is not None:
                obj.id = existing_dp.id
            obj.save()
            
            

            data['status'] = 1
            

    data = json.dumps(data)
    messages.success(request,'Successfully Uploaded!')
    return HttpResponse(data, content_type='application/json')
    return HttpResponseRedirect('/insta/viewprofile')
    

def post_photo_comment(request):
    data = {
        'status': 0
    }

    if request.user.is_authenticated and request.method == 'POST':
        post_data = request.POST

        photo = get_object_or_None(Photo, pk=post_data['photo_id'])
        comment = Comment(
            owner=request.user.member,
            photo=photo,
            text=post_data['comment_text']
            )
        resp = comment.save()
        data['status'] = 1

    data = json.dumps(data)
    return HttpResponse(data, content_type='application/json')

def like_photo(request):
    data = {
        'status': 0
    }

    # TODO: Check if like already exists
    if request.user.is_authenticated and request.method == 'POST':
        post_data = request.POST

        photo = get_object_or_None(Photo, pk=post_data['photo_id'])

        check_like = get_object_or_None(Like,
            owner=request.user.member,
            photo=photo
            )

        if check_like is None:
            like = Like(
                owner=request.user.member,
                photo=photo,
                )
            like.save()
            data['status'] = 1

    data = json.dumps(data)
    return HttpResponse(data, content_type='application/json')

djinstagram/instaapp/views/general.py
# TODO[10.6.2016]: Refactor code, remove unused imports
# TODO[10.6.2016]: Refactor code, remove unused imports
# Normal views

import json, itertools

from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

from django.core.exceptions import MultipleObjectsReturned

from instaapp.forms import LoginForm, PhotoForm, MemberPhotoForm, SuggestForm
from instaapp.models import Follow, Photo, Member, Comment, Like, Suggestion

from annoying.functions import get_object_or_None
from operator import attrgetter
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm
from .forms import UserRegisterForm
from django.contrib.auth import get_user_model



# Create your views here.

def is_authenticated(self):
    return True

def index(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect('/insta/feed')
    return render(request, 'instaapp/index.html', {})



@login_required
def home(request):
    if request.user.is_authenticated:
        user = User.objects.get(pk=request.user.id)

        memberphoto = get_object_or_None(Member, user=user)
        if memberphoto is not None:
            return HttpResponseRedirect('/insta/feed')
        else:
            messages.error(request,'Please add your Profile Picture first')
            
       

    return render(request, 'instaapp/feed.html', {})




def feed(request):
    """
    View that displays the uploaded photos of users that the
    `logged user` follows
    """
    user = request.user
    photos = []
    liked_photos = []
    user_following = Follow.objects.filter(follower__id=user.id)

    for user_object in user_following:
        following_photos = Photo.objects.filter(owner__id=user_object.following.id)

        if following_photos is not None:
            photos.append(following_photos)

    # flatten list of photos
    chain = itertools.chain(*photos)
    photos = sorted(list(chain),
            key=attrgetter('created'), reverse=True)

    for photo in photos:
        photo_like = get_object_or_None(Like,
            owner=user.member,
            photo=photo
            )
        if photo_like:
            liked_photos.append(photo.pk)

    return render(request, 'instaapp/feed.html', {
        'photos': photos,
        'liked_photos': liked_photos
        })

def user_login(request):
    form = LoginForm()

    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)

        if user is not None:
            login(request, user)
            return HttpResponseRedirect('/insta')

        else:
            messages.error(request,'Incorrect Account or Does Not Exist')
            #return HttpResponse('Invalid Login')

    else:
        form = LoginForm()

    return render(request, 'instaapp/login.html', {'form': form})



def user_logout(request):
    logout(request)
    return HttpResponseRedirect('/insta/login')

@login_required
def upload_photo(request):
    """
    Method that lets user upload an image
    """
    uploader = request.user
    form = PhotoForm()

    if request.method == 'POST':
        form = PhotoForm(request.POST, request.FILES)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.owner = uploader
            obj.save()
            form = PhotoForm()
            messages.success(request,'Successfully Uploaded! ')
            return HttpResponseRedirect('/insta/upload')
        

    else:
        form = PhotoForm()

    return render(request, 'instaapp/upload_photo.html', {'form': form})

@login_required
def user_profile(request, username=None):
    """
    View to display the `logged user's` profile and uploaded photos
    """

    upload_prof_pic_form = MemberPhotoForm()

    if username is None:
        user = request.user

    else:
        user = User.objects.get(username=username)

    dp_obj = get_object_or_None(Member, user__pk=user.id)
    if dp_obj is None:
        user_dp = False
    else:
        user_dp = dp_obj

    user_photos = Photo.objects.filter(owner__pk=user.id)
    photos_count = user_photos.count()
    

    #if user_dp is False:
       # return render(request, 'instaapp/profile.html', {
           # 'user': user,
          #  'user_dp': user_dp,
          #  'photos': user_photos,
          #  'count': photos_count,
         #   'dp_form': upload_prof_pic_form
           # })
   # else:
       # return HttpResponseRedirect('/insta/feed')

def viewprofile(request, username=None):
    upload_prof_pic_form = MemberPhotoForm()

    if username is None:
        user = request.user

    else:
        user = User.objects.get(username=username)

    dp_obj = get_object_or_None(Member, user__pk=user.id)
    if dp_obj is None:
        user_dp = False
    else:
        user_dp = dp_obj

    user_photos = Photo.objects.filter(owner__pk=user.id)
    photos_count = user_photos.count()

    
    return render(request, 'instaapp/profile.html', {
        'user': user,
        'user_dp': user_dp,
        'photos': user_photos,
        'count': photos_count,
        'dp_form': upload_prof_pic_form
        })

def users(request):
    """
    View to display a list of all users registered to the app
    """
    userlist = []
    users = User.objects.all()[:10]

    for user in users:
        queryset = Follow.objects.filter(
                            follower__pk=request.user.id,
                            following__pk=user.pk,
                            active=True
                            )
        follow_status = get_object_or_None(queryset)

        if follow_status is None:
            userlist.append(user)

    return render(request, 'instaapp/users.html', {'users': userlist})

def signup(request):
    if request.method =='POST':
        form = UserRegisterForm(request.POST)
 
        if form.is_valid():
            instance = form.save(commit=False)
            instance.save()
            username = form.cleaned_data.get('username')
            return HttpResponseRedirect('/insta/login')
        else:
            messages.error(request, 'Check For Errors')
    else:    
        form = UserRegisterForm()
    return render(request, 'instaapp/signup.html', {'form': form})

#return render(request, 'instaapp/signup.html')

@login_required
def user_following(request):
    """
    View to display a list of users that the `logged user` is following
    """
        
    user = request.user

    following = Follow.objects.filter(follower__pk=user.id, active=True)
    
    

    

    return render(request, 'instaapp/user_following.html', {
        'following': following
        })


@login_required
def user_followers(request):
    """
    View to display a list of users who follow the `logged user`
    """



    followers = Follow.objects.filter(following__pk=request.user.id)

    #Check if you follow the users who follow you
    if request.user.is_authenticated:
        for user in followers:
            queryset = Follow.objects.filter(
            follower__id=request.user.id,
            following__id=user.follower.id
            )
            user.is_followed = get_object_or_None(queryset)
        

    

    
    return render(request, 'instaapp/user_followers.html', {
        'followers': followers,
        })

def search(request):
    query = request.GET.get('q', '')

    followlist = []
    results = User.objects.filter(username__contains=query)

    # Check follow status on a result
    if request.user.is_authenticated:
        for user in results:
            queryset = Follow.objects.filter(
                                follower__pk=request.user.id,
                                following__pk=user.pk,
                                active=True
                                )
            follow_status = get_object_or_None(queryset)

            if follow_status is not None:
                followlist.append(user.id)
            

    return render(request, 'instaapp/search.html', {
        'results': results,
        'followlist': followlist
        })

def otherprofile(request, username=None):

    #upload_prof_pic_form = MemberPhotoForm()

    if username is None:
        user = request.user

    else:
        user = User.objects.get(username=username)

    dp_obj = get_object_or_None(Member, user__pk=user.id)
    if dp_obj is None:
        user_dp = False
    else:
        user_dp = dp_obj

    user_photos = Photo.objects.filter(owner__pk=user.id)
    photos_count = user_photos.count()
    #suggest = Suggestion.objects.filter(owner_pk=user.id)
    # x = User.objects.get(pk=request.user.id)

    text = Suggestion.objects.filter(owner__pk=user.id)
    # text = Suggestion.filter.values_list('text', flat=True)

   

    
    
        


    
    
    
    

    
    return render(request, 'instaapp/otherprofile.html', {
        'user': user,
        'user_dp': user_dp,
        'photos': user_photos,
        'count': photos_count,
        'text':text,
        })

def suggest(request):
    form = SuggestForm()
    if request.user.is_authenticated:
        if request.method == 'POST':
            form = SuggestForm(request.POST)
            if form.is_valid():
                instance = form.save(commit=False)
                instance.owner = request.user
                instance.save()
                return HttpResponseRedirect('/insta/addsuggest')   
    return render(request, 'instaapp/suggestions.html', {'form':form})

def delsuggest(request, username=None):
    user = request.user
    text = Suggestion.objects.filter(owner__pk=user.id)

    if request.user.is_authenticated:
        if request.method == 'POST':
            instance = Suggestion.objects.filter(owner__pk=user.id)

djinstagram/instaapp/templates/instaapp/includes/foot.html
{% load staticfiles %}
    <br />
    <footer>
        Django Instagram Clone &copy; cflauta
    </footer>

    <script src="{% static "instaapp/js/jquery-1.12.4.min.js" %}"></script>
    <script src="{% static "instaapp/js/js.cookie.js" %}"></script>
    <script src="{% static "instaapp/js/scripts.js" %}"></script>
    <script src="{% static "instaapp/js/bootstrap.min.js" %}"></script>
    </body>
</html>

djinstagram/instaapp/templates/instaapp/includes/head.html
{% load staticfiles %}
<!doctype html>
<html>
    <head>
        <title>IGClone</title>

        <link rel="stylesheet" href="{% static "instaapp/css/bootstrap.min.css" %}">
        <link rel="stylesheet" href="{% static "instaapp/css/style.css" %}">

    </head>

    <body>

djinstagram/instaapp/templates/instaapp/includes/nav.html
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'instaapp:home' %}"></a>
        </div>
        {% if user.is_authenticated %}
               
        asdasdasds
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">

                    
                <li>
                    <a href="{% url 'instaapp:user_following' %}">
                    Following
                    </a>
                </li>
                <li>
                    <a href="{% url 'instaapp:user_followers' %}">
                    Followers
                    </a>
                </li>
            </ul>

            <form
                action="{% url 'instaapp:user_search' %}"
                method="GET"
                id="formSearch"
                class="navbar-form navbar-left"
                role="search">
                <div class="form-group">
                  <input
                        name="q"
                        type="text"
                        class="form-control"
                        placeholder="Search">
                </div>
                <button type="submit" class="btn btn-default">Submit</button>
            </form>
            {% else %}

        {% endif %}
            <ul class="nav navbar-nav navbar-right">
                
                <li>
                    <a href="{% url 'instaapp:users' %}">Users</a>
                </li>
                {% if user.is_authenticated %}
               
                {% else %} 
                <li>
                        <a href="{% url 'instaapp:signup' %}">Sign up</a>
                    </li>
                {% endif %}
                {% if user.is_authenticated %}
                    <li class="dropdown">
                        <a
                            href="#"
                            class="dropdown-toggle"
                            data-toggle="dropdown"
                            role="button"
                            aria-haspopup="true"
                            aria-expanded="false">{{user.username}} <span class="caret"></span></a>

                        <ul class="dropdown-menu">
                            <li>
                                <a href="{% url 'instaapp:viewprofile' %}">Upload Profile Picture</a>
                            </li>
                            <li>
                                <a href="{% url 'instaapp:otherprofile' %}">View Profile</a>
                            </li>
                            <li>
                                <a href="{% url 'instaapp:suggest' %}">Add Suggestion</a>
                            </li>
                            <li>
                                <a href="{% url 'instaapp:delsuggest' %}">Delete Suggestion</a>
                            </li>
                            <li>
                                <a href="{% url 'instaapp:upload_photo' %}">Upload a Photo</a>
                            </li>
                            <li role="separator" class="divider"></li>
                            <li>
                                <a href="{% url 'instaapp:user_logout' %}">Logout</a>
                            </li>
                        </ul>
                    </li>
                {% else %}
                    <li>
                        <a href="{% url 'instaapp:user_login' %}">Login</a>
                    </li>
                {% endif %}
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>