djinstagram/djinstagram/urls.py
from django.conf.urls import url, include
from django.urls import path
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

from instaapp.views import general

urlpatterns = [
    url(r'^$', general.index, name='instaindex'),
    url(r'^admin/', admin.site.urls),
    url(r'^insta/', include('instaapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djinstagram/instaapp/urls.py
from django.conf.urls import url
from django.urls import path
from .views import ajax
from .views import general

app_name = 'instaapp'
urlpatterns = [
    url(r'^$', general.index, name='index'),
    url(r'^login/$', general.user_login, name='user_login'),
    url(r'^viewprofile/$', general.viewprofile, name='viewprofile'),
    url(r'^home/$', general.home, name='home'),
    url(r'^logout/$', general.user_logout, name='user_logout'),
    url(r'^upload/$', general.upload_photo, name='upload_photo'),
    url(r'^users/$', general.users, name='users'),
    url(r'^signup/$', general.signup, name='signup'),
    url(r'^u/(?P<username>[\w-]+)$', general.user_profile, name='user_view'),
    url(r'^profile/$', general.user_profile, name='user_profile'),
    url(r'^following/$', general.user_following, name='user_following'),
    url(r'^followers/$', general.user_followers, name='user_followers'),
    url(r'^feed/$', general.feed, name='feed'),
    url(r'^search/$', general.search, name='user_search'),
    url(r'^otherprofile/$', general.otherprofile, name='otherprofile'),
    url(r'^addsuggest/$', general.suggest, name='suggest'),
    url(r'^delsuggest/$', general.delsuggest, name='delsuggest'),
 

    # AJAX methods
    url(r'^upload_dp/$', ajax.upload_user_profile_pic,
        name='upload_user_profile_pic'),
    url(r'^follow/$', ajax.follow_user, name='follow_user'),
    url(r'^unfollow/$', ajax.unfollow_user, name='unfollow_user'),
    url(r'^post_comment/$', ajax.post_photo_comment, name='post_photo_comment'),
    url(r'^like_comment/$', ajax.like_photo, name='like_photo'),
]

djinstagram/instaapp/models.py
from django.db import models

from django.contrib.auth.models import User

# Create your models here.

class Follow(models.Model):
    follower = models.ForeignKey(User, related_name='+', null=True, on_delete=models.CASCADE)
    following = models.ForeignKey(User,  related_name='+', null=True, on_delete=models.CASCADE)
    active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)

    def get_follower(self):
        return self.follower

    def get_following(self):
        return self.following

class Tag(models.Model):
    name = models.TextField(max_length=255)

    def __str__(self):
        return self.name

class Photo(models.Model):
    owner = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    caption = models.TextField(max_length=255)
    image = models.ImageField(upload_to="uploads/photos", null=True)
    tags = models.ManyToManyField(Tag)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.caption

    def image_tag(self):
        return u'<img src="%s" />' % self.image.url

    image_tag.short_description = 'Image Preview'
    image_tag.allow_tags = True

class Member(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="uploads/dp", null=True)
    modified = models.DateTimeField(auto_now=True, null=True)

    def __str__(self):
        return self.user.username
    

class Like(models.Model):
    owner = models.ForeignKey(Member, null=True, on_delete=models.CASCADE)
    photo = models.ForeignKey(Photo, null=True, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def image_tag(self):
        return u'<img src="%s" />' % self.photo.image.url

    image_tag.short_description = 'Image with tags'
    image_tag.allow_tags = True

class Comment(models.Model):
    owner = models.ForeignKey(Member, null=True,on_delete=models.CASCADE)
    photo = models.ForeignKey(Photo, null=True, on_delete=models.CASCADE)
    text = models.TextField(max_length=255)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.text

class Suggestion(models.Model):
    owner = models.ForeignKey(User, null = True, on_delete=models.CASCADE)
    text = models.TextField(max_length=255, null=True)

    def __str__(self):
        return self.text
    
    def get_owner(self):
        return self.owner

      
    

djinstagram/instaapp/forms.py
from django import forms
from .models import Photo, Member, Suggestion

class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control'
        }
        ))
    password = forms.CharField(widget=forms.PasswordInput(
        attrs = {
            'class': 'form-control'
        }
        ))

class PhotoForm(forms.ModelForm):
    class Meta:
        model = Photo
        fields = ('image', 'caption',)
        widgets = {
            'caption': forms.Textarea(attrs={
                'class': 'form-control',
                'rows': 3
                })
        }
    #field_order = ['created']

class MemberPhotoForm(forms.ModelForm):
    class Meta:
        model = Member
        fields = ('image',)

class SuggestForm(forms.ModelForm):

    class Meta:
        model = Suggestion
        fields = ('text', )

djinstagram/instaapp/views/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()
    

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

djinstagram/instaapp/views/ajax.py
# TODO[10.6.2016]: Refactor code, remove unused imports
# Views for AJAX Requests

import json, itertools

from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect

from django.core.exceptions import MultipleObjectsReturned
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

from instaapp.forms import LoginForm, PhotoForm, MemberPhotoForm
from instaapp.models import Follow, Photo, Member, Comment, Like

from annoying.functions import get_object_or_None
from django.contrib import messages
# Create your views here.

def follow_user(request):
    """
    Method (AJAX) that makes the `logged user` follow the selected user
    """
    data = {
            'status': 0,
        }
    if request.user.is_authenticated:
        if request.method == 'POST':
            follower = User.objects.get(pk=request.user.id)
            following = User.objects.get(pk=request.POST['uid'])
            try:
                follow = Follow(follower=follower, following=following)
                follow.save()
               
            except Follow.MultipleObjectsReturned:
                pass
        
            data = {
                    'status': 1,
                    'follower': request.user.id,
                    'to_follow': request.POST['uid']
                }

            # data to be returned as json

            
    data = json.dumps(data)
    return HttpResponse(data, content_type='application/json')

def unfollow_user(request):
    """
    Method (AJAX) that makes the `logged user` to unfollow a selected user
    """
    data = {
        'status': 0,
    }
    if request.user.is_authenticated:
        if request.method == 'POST':
            # check if logged user is following the selected user
            x = User.objects.get(pk=request.user.id)
            y = User.objects.get(pk=request.POST['uid'])
            
            # follow_obj = get_object_or_None(Follow,
            #                         follower=follower,
            #                         following=following, 
            #                         active=True
            #                         )
            for zzz in Follow.objects.all(): 
                try:
                    follow_obj = Follow.objects.get(follower=x, following=y)
                    follow_obj.delete()
                    data['status'] = 1
               
               
                except Follow.DoesNotExist:
                    pass
                except Follow.MultipleObjectsReturned:
                    dups = Follow.objects.filter(follower=x, following=y)
                    perm = dups[0]
                    for dup in dups[1:]:
                        dup.delete()
                        data['status'] = 1

    data = json.dumps(data)
    return HttpResponse(data, content_type='application/json')

def upload_user_profile_pic(request):
    """
    Method (AJAX) that allows the `logged user` to upload a profile pic
    """
    uploader = request.user
    form = MemberPhotoForm()
    data = {
        'status': 1,
    }

    if request.method == 'POST':
        form = MemberPhotoForm(request.POST, request.FILES)
        if form.is_valid():

            # check if user has already uploaded a profile picture
            existing_dp = get_object_or_None(Member, user__pk=uploader.id)

            obj = form.save(commit=False)
            obj.user = uploader

            if existing_dp is not None:
                obj.id = existing_dp.id
            obj.save()
            
            

            data['status'] = 1
            

    data = json.dumps(data)
    messages.success(request,'Successfully Uploaded!')
    return HttpResponse(data, content_type='application/json')
    return HttpResponseRedirect('/insta/viewprofile')
    

def post_photo_comment(request):
    data = {
        'status': 0
    }

    if request.user.is_authenticated and request.method == 'POST':
        post_data = request.POST

        photo = get_object_or_None(Photo, pk=post_data['photo_id'])
        comment = Comment(
            owner=request.user.member,
            photo=photo,
            text=post_data['comment_text']
            )
        resp = comment.save()
        data['status'] = 1

    data = json.dumps(data)
    return HttpResponse(data, content_type='application/json')

def like_photo(request):
    data = {
        'status': 0
    }

    # TODO: Check if like already exists
    if request.user.is_authenticated and request.method == 'POST':
        post_data = request.POST

        photo = get_object_or_None(Photo, pk=post_data['photo_id'])

        check_like = get_object_or_None(Like,
            owner=request.user.member,
            photo=photo
            )

        if check_like is None:
            like = Like(
                owner=request.user.member,
                photo=photo,
                )
            like.save()
            data['status'] = 1

    data = json.dumps(data)
    return HttpResponse(data, content_type='application/json')

djinstagram/instaapp/templates/instaapp/delsuggest.html
{% load staticfiles %}
{% include 'instaapp/includes/head.html' %}
{% include 'instaapp/includes/nav.html' %}
<div id="content" class="container">
    
        <div class="col-sm-6 col-sm-offset-3">
    <h3>Suggested Users: 
        {% if text %}
            {% for x in text %}
                {{x}}
            {% endfor %}
            {% else %}
            Nobody atm...</h3>
        {% endif %}
    <br>
    <br>
                            <form 
                                method="post"
                                action="{% url 'instaapp:delsuggest' %}"
                                class="comment-form">
                                {% csrf_token %}
                                
                                <button class="btn btn-primary btn-block" type="submit">Delete</button>
                            </form>
    
                        </div>
        

</div>
<!-- <body oncontextmenu="return false;"> -->
{% include 'instaapp/includes/foot.html' %}
<script src="{% static "instaapp/js/jquery.form.min.js" %}"></script>
<script src="{% static "instaapp/js/profile.js" %}"></script>

djinstagram/instaapp/templates/instaapp/feed.html
{% load staticfiles %}
{% include 'instaapp/includes/head.html' %}
{% include 'instaapp/includes/nav.html' %}
<body oncontextmenu="return false;">
<div id="content" class="container">

    <div class="col-sm-6 col-sm-offset-3">
            {% for message in messages %}
            <div class="alert alert-danger">
                <center><a class="close" href="#" data-dismiss="alert">×</a>
    
                {{ message }}
            </center>
    
            </div> 
            {% endfor %}
        <h1>Feed</h1>
        {% if photos %}
            {% for photo in photos %}
                <div class="panel panel-default panel-post">
                    <div class="panel-heading">
                        {% if photo.owner.member.image.url %}
                            <img
                                src="{{ MEDIA_URL }}{{photo.owner.member.image.url}}"
                                alt="avatar"
                                class="img-avatar img-thumbnail">
                        {% else %}
                            <img
                                src="{% static "instaapp/img/profile-picture-placeholder.png" %}"
                                alt="dp"
                                class="img-avatar img-thumbnail">
                        {% endif %}
                        <span class="panel-title">{{photo.owner.username}}</span>
                        <span class="pull-right">{{photo.created|timesince}}</span>
                        <p>{{photo.member}}</p>
                    </div>
                    <div class="panel-body">
                        <img src="{{ MEDIA_URL }}{{photo.image.url}}" alt="post" />
                    </div>
                    <div class="panel-footer">
                        <p><strong>{{photo.like_set.all.count}}</strong> likes</p>
                        <p>
                            <strong>{{photo.owner.username}}</strong>
                            &nbsp;{{photo.caption}}
                        </p>
                        {% for comment in photo.comment_set.all %}
                            <p class="photo-comment">
                                <strong>{{comment.owner}}</strong>
                                &nbsp;{{comment.text}}
                            </p>
                        {% endfor %}
                        <hr />
                        <div class="input-group input-group-sm">
                            {# Like photo button #}

                            <span
                                data-pid="{{photo.id}}"
                                data-url="{% url 'instaapp:like_photo' %}"
                                {% if photo.pk in liked_photos %}
                                    class="input-group-addon like-button liked_photo"
                                {% else %}
                                    class="input-group-addon like-button"
                                {% endif %}
                                >
                                <span class="glyphicon glyphicon-heart"></span>
                            </span>

                            {# Comment text box #}
                            <form 
                                onsubmit="return false"
                                method="post"
                                action="{% url 'instaapp:post_photo_comment' %}"
                                class="comment-form">
                            {% csrf_token %}
                                <input
                                    type="hidden"
                                    name="photo_id"
                                    value="{{photo.id}}" />
                                <input
                                    name="comment_text"
                                    type="text"
                                    class="form-control"
                                    placeholder="Say something..."
                                    aria-describedby="sizing-addon3" />
                            </form>

                            {# Options dropdown #}
                            <div class="input-group-btn">
                                <button
                                type="button"
                                class="btn btn-default dropdown-toggle"
                                data-toggle="dropdown"
                                aria-haspopup="true"
                                aria-expanded="false">
                                    <span
                                    class="pull-right glyphicon glyphicon-option-horizontal"></span>
                                </button>
                                <ul class="dropdown-menu dropdown-menu-right">
                                    <li><a href="#">Action</a></li>
                                    <li><a href="#">Another action</a></li>
                                    <li><a href="#">Something else here</a></li>
                                    <li role="separator" class="divider"></li>
                                    <li><a href="#">Separated link</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <div class="alert alert-info">
                You are not following any users or No post have been uploaded yet. <br>
                <a href="{% url 'instaapp:users' %}">Follow</a> users to view photos.
            </div>
        {% endif %}

    </div>

</div>
{% include 'instaapp/includes/foot.html' %}
<script src="{% static "instaapp/js/jquery.form.min.js" %}"></script>
<script src="{% static "instaapp/js/photo-user-actions.js" %}"></script>

djinstagram/instaapp/templates/instaapp/index.html
{% load staticfiles %}
{% include 'instaapp/includes/head.html' %}
{% include 'instaapp/includes/nav.html' %}
<div id="content" class="container">
    <div class="col-sm-6 col-sm-offset-3">
        <center><h1 >Welcome to Exchange A Gram!</h1></center>
    </div>


</div>
<!--body oncontextmenu="return false;"> -->
{% include 'instaapp/includes/foot.html' %}

djinstagram/instaapp/templates/instaapp/login.html
{% load staticfiles %}
{% load crispy_forms_tags %}
{% include 'instaapp/includes/head.html' %}
{% include 'instaapp/includes/nav.html' %}

    <div class="col-sm-6 col-sm-offset-3">
        <h3>Login</h3>
        <form action="" method="post">
        {% csrf_token %}
            {{form|crispy}}
            <div class="form-group">
                    <button class="btn btn-primary btn-block" type="submit">Sign In</button> <center><small class="text-muted">Don't have an Account? <a class="ml-2" href="{% url 'instaapp:signup' %}">Sign Up</a></small></center>
                </div>
        </form>
    {% for message in messages %}

                    <div class="alert alert-danger">
                        <a class="close" href="#" data-dismiss="alert">×</a>

                        {{ message }}

                    </div>
    {% endfor %}

    </div>
<!-- <body oncontextmenu="return false;"> -->
</div>

{% include 'instaapp/includes/foot.html' %}

djinstagram/instaapp/templates/instaapp/otherprofile.html
{% load staticfiles %}
{% include 'instaapp/includes/head.html' %}
{% include 'instaapp/includes/nav.html' %}
<div id="content" class="container">
    <div class="col-sm-6 col-sm-offset-3">
        <div class="row">
            <div class="col-sm-4">

                {% if user_dp %}
                    <img src="{{ MEDIA_URL }}{{user_dp.image.url}}" alt="dp" class="img-thumbnail img-responsive">
                {% else %}
                    <img src="{% static "instaapp/img/profile-picture-placeholder.png" %}" alt="dp" class="img-thumbnail img-responsive">
                {% endif %}
              
                 
            </div>
            <div class="col-sm-8">
                <h1>@{{user.username}} <small>{{user.first_name}} {{user.last_name}}</small></h1>
                <span>{{count}} posts</span>
            </div>
        </div>
<br>

    <h3>Suggested Users: 
        {% if text %}
            {% for x in text %}
                {{x}}
            {% endfor %}
            {% else %}
            Nobody atm...</h3>
        {% endif %}

        
        

        <br>
        <div class="row">
            
                  
            <hr>
            
            {% for photo in photos %}
                <div class="col-sm-3">
                    <img class="img-responsive img-rounded" src="{{ MEDIA_URL }}{{photo.image.url}}" alt="{{photo.caption}}" title="{{photo.caption}}"/>
                </div>
            {% endfor %}
        </div>
    </div>

</div>
<!-- <body oncontextmenu="return false;"> -->
{% include 'instaapp/includes/foot.html' %}
<script src="{% static "instaapp/js/jquery.form.min.js" %}"></script>
<script src="{% static "instaapp/js/profile.js" %}"></script>

djinstagram/instaapp/templates/instaapp/profile.html
{% load staticfiles %}
{% include 'instaapp/includes/head.html' %}
{% include 'instaapp/includes/nav.html' %}
<div id="content" class="container">
    <div class="col-sm-6 col-sm-offset-3">
        <div class="row">
            <div class="col-sm-4">

                {% if user_dp %}
                    <img src="{{ MEDIA_URL }}{{user_dp.image.url}}" alt="dp" class="img-thumbnail img-responsive">
                {% else %}
                    <img src="{% static "instaapp/img/profile-picture-placeholder.png" %}" alt="dp" class="img-thumbnail img-responsive">
                {% endif %}
                <form id="uploadDp" action="{% url 'instaapp:upload_user_profile_pic' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{dp_form}}
                    <button type="submit" class="btn btn-primary btn-upload" method="POST">
                        Upload
                    </button>

                </form>
                 
            </div>
            <div class="col-sm-8">
                <h1>@{{user.username}} <small>{{user.first_name}} {{user.last_name}}</small></h1>
                
            </div>
        </div>

        <div class="row">
                {% for message in messages %}

    <div class="alert alert-success">
                    <a class="close" href="#" data-dismiss="alert">×</a>

                    {{ message }}

    </div>
             {% endfor %}        
            
        </div>
    </div>

</div>
<!-- <body oncontextmenu="return false;"> -->
{% include 'instaapp/includes/foot.html' %}
<script src="{% static "instaapp/js/jquery.form.min.js" %}"></script>
<script src="{% static "instaapp/js/profile.js" %}"></script>

djinstagram/instaapp/templates/instaapp/search.html
{% load staticfiles %}
{% include 'instaapp/includes/head.html' %}
{% include 'instaapp/includes/nav.html' %}
<div id="content" class="container">
    <div class="col-sm-6 col-sm-offset-3">
        <h1>Search Results</h1>

        {% for user in results %}
            <div class="well user-card">
                {% if user.member.image.url %}
                    <img
                        src="{{ MEDIA_URL }}{{user.member.image.url}}"
                        alt="{{user.username}}"
                        class="img-avatar img-thumbnail" />
                {% else %}
                    <img
                        src="{% static "instaapp/img/profile-picture-placeholder.png" %}"
                        alt="dp"
                        class="img-avatar img-thumbnail">
                {% endif %}
                <span>
                    <strong>{{user.first_name}} {{user.last_name}}</strong> <small>@{{user.username}}</small>
                </span>

                {% if user.id in followlist %}
                    <button class="btn btn-success disabled pull-right">
                        <span class="glyphicon glyphicon-ok"></span>
                        Followed
                    </button>
                {% else %}
                    <button
                        class="btn btn-success pull-right btn-follow"
                        data-user="{{user.id}}">
                        <span class="glyphicon glyphicon-plus"></span>
                        Follow
                    </button>
                {% endif %}
            </div>
        {% endfor %}
    </div>

</div>

<div id="notLoggedInModal" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body">
                <p>You are not logged in.</p>
                <p>To follow this user, login <a href="{% url 'instaapp:user_login' %}">here</a></p>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

{% include 'instaapp/includes/foot.html' %}
<script src="{% static "instaapp/js/follow.js" %}"></script>

djinstagram/instaapp/templates/instaapp/signup.html
{% load staticfiles %}
{% load crispy_forms_tags %}
{% include 'instaapp/includes/head.html' %}
{% include 'instaapp/includes/nav.html' %}

<div class="content-section">
    <div class="col-sm-6 col-sm-offset-3">
        <form method="POST">
            {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Register Now</legend>
                    {{ form|crispy }}
                </fieldset>
                {% for message in messages %}
                <div class="alert alert-danger">
                    <a class="close" href="#" data-dismiss="alert">×</a>

                    {{ message }}

                </div>
                {% endfor %}
                <div class="form-group">
                    <button class="btn btn-block btn-primary" type="submit">Sign Up</button> <center><small class="text-muted">Already Have an Account? <a class="ml-2" href="{% url 'instaapp:user_login' %}">Sign In</a></small></center>
                </div>

        </form>
        
    

    </div>
<body oncontextmenu="return false;">
</div>


{% include 'instaapp/includes/foot.html' %}

djinstagram/instaapp/templates/instaapp/suggestions.html
{% load staticfiles %}
{% include 'instaapp/includes/head.html' %}
{% include 'instaapp/includes/nav.html' %}

<div class="content-section container" >
    <h3>Add Suggestion</h3>
   
                            <form 
                                method="post"
                                action="{% url 'instaapp:suggest' %}"
                                class="comment-form">
                                {% csrf_token %}
                                {{form.as_p}}<br>
                                <button class = "btn btn-primary" type="submit">Send</button>
                            </form>
                            
                        </div>
{% include 'instaapp/includes/foot.html' %}

djinstagram/instaapp/templates/instaapp/upload_photo.html
{% load staticfiles %}
{% include 'instaapp/includes/head.html' %}
{% include 'instaapp/includes/nav.html' %}
<div id="content" class="container">
    <div class="col-sm-6 col-sm-offset-3">
        <h1>Upload a Photo</h1>
        <form action="" method="post"  enctype="multipart/form-data">
            {% csrf_token %}
            {{form.as_p}}
            <button class="btn btn-primary" type="submit">Upload</button>
        </form>
        <br>
        {% for message in messages %}

                    <div class="alert alert-success">
                        <a class="close" href="#" data-dismiss="alert">×</a>

                        {{ message }}

                    </div>
    {% endfor %}
    </div>
     
</div>
{% include 'instaapp/includes/foot.html' %}

djinstagram/instaapp/templates/instaapp/user_following.html
{% load staticfiles %}
{% include 'instaapp/includes/head.html' %}
{% include 'instaapp/includes/nav.html' %}
<div id="content" class="container">
    <div class="col-sm-6 col-sm-offset-3 users-list">
        <h2>Users that you Follow</h2>
        {% if following %}
        {% for user in following %}
            <div class="col-sm-12">
                <div class="row">
                    <div class="well">
                        <img class="img-circle" src="{% static "instaapp/img/30avatar.png" %}" alt="following avatar">
                        <span>{{user.following}}</span>        
                        <button
                            data-user="{{user.following.id}}"
                            class="btn btn-primary pull-right btn-following" >
                            <span class="glyphicon glyphicon-ok"></span>
                            <span class="text">Following</span>
                        </button>
                    
                    </div>
                </div>
            </div>
        {% endfor %}
        {% else %}
        <div class="alert alert-info">
                You are not following any users. <a href="{% url 'instaapp:users' %}">Follow</a> users to view photos.
            </div>
        {% endif %}
    </div>
</div>
{% include 'instaapp/includes/foot.html' %}
<script src="{% static "instaapp/js/follow.js" %}"></script>

djinstagram/instaapp/templates/instaapp/users.html
{% load staticfiles %}
{% include 'instaapp/includes/head.html' %}
{% include 'instaapp/includes/nav.html' %}
<div id="content" class="container">
    <div class="col-sm-6 col-sm-offset-3 users-list">
        <h1>Users to Follow</h1>
        {% for user in users %}
            <div class="well user-card">
                {% if user.member.image.url %}
                    <img
                        src="{{ MEDIA_URL }}{{user.member.image.url}}"
                        alt="{{user.username}}"
                        class="img-avatar img-thumbnail" />
                {% else %}
                    <img
                        src="{% static "instaapp/img/profile-picture-placeholder.png" %}"
                        alt="dp"
                        class="img-avatar img-thumbnail">
                {% endif %}
                <span>
                    <strong>{{user.first_name}} {{user.last_name}}</strong> <small>@{{user.username}}</small>
                </span>

                {% if user.is_followed %}
                    <button class="btn btn-success disabled pull-right">
                        <span class="glyphicon glyphicon-ok"></span>
                        Followed
                    </button>
                {% else %}
                    <button
                        class="btn btn-success pull-right btn-follow"
                        data-user="{{user.id}}">
                        <span class="glyphicon glyphicon-plus"></span>
                        Follow
                    </button>
                {% endif %}
            </div>
        {% endfor %}
    </div>

</div> <!-- / #content -->

<div id="notLoggedInModal" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body">
                <p>You are not logged in.</p>
                <p>To follow this user, login <a href="{% url 'instaapp:user_login' %}">here</a></p>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
{% include 'instaapp/includes/foot.html' %}
<script src="{% static "instaapp/js/follow.js" %}"></script>